name: Deploy android to Google Play
on:
  push:
    branches:
      - master
jobs:
  install-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn
      - name: Build android aab
        run: |
          cd android
          echo "TACHELHIT_KEY_ALIAS=${{ secrets.TACHELHIT_KEY_ALIAS }}" >> gradle.properties
          echo "TACHELHIT_UPLOAD_STORE_FILE=${{ secrets.TACHELHIT_UPLOAD_STORE_FILE }}" >> gradle.properties
          echo "TACHELHIT_UPLOAD_STORE_PASSWORD=${{ secrets.TACHELHIT_UPLOAD_STORE_PASSWORD }}" >> gradle.properties
          echo "TACHELHIT_UPLOAD_KEY_PASSWORD=${{ secrets.TACHELHIT_UPLOAD_KEY_PASSWORD }}" >> gradle.properties
          ./gradlew bundleRelease
      - name: upload bundle to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
          packageName: com.tachelhitinfo
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          track: production
          #userFraction: 0.33
          whatsNewDirectory: whatsnew
          #mappingFile: /app/build/outputs/mapping/release/mapping.txt
